# Generated by Django 3.1.1 on 2021-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('youremail', models.CharField(max_length=50)),
                ('websitename', models.CharField(max_length=50)),
                ('yourmessage', models.CharField(max_length=100)),
            ],
        ),
    ]
