# Generated by Django 3.1.1 on 2021-03-10 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_remove_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(max_length=200)),
                ('blogTitle', models.CharField(max_length=200)),
                ('blogCatagories', models.CharField(max_length=100)),
                ('blogAuthor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.blogtemplate')),
            ],
        ),
    ]
