# Generated by Django 3.1.1 on 2021-03-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_articledetail_articleauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='articleAuthor',
        ),
    ]
