# Generated by Django 3.1.1 on 2021-03-17 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_articledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='blogDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
