# Generated by Django 3.1.1 on 2021-03-19 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0018_blogdetails_blogdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSociallink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociallinkName', models.CharField(max_length=200)),
                ('sociallink', models.URLField()),
                ('linkUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
