# Generated by Django 3.1.1 on 2021-03-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=200)),
                ('subscribeTo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.blogdetails')),
            ],
        ),
    ]
