# Generated by Django 3.1.1 on 2021-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210323_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriber',
            name='subscribeTo',
            field=models.CharField(max_length=100),
        ),
    ]
