# Generated by Django 3.1.1 on 2021-03-27 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20210324_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
