# Generated by Django 3.1.1 on 2021-04-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_comment_commentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='articleKeyword',
        ),
    ]
