# Generated by Django 3.1.1 on 2021-04-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_articledetail_articlekeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentbyEmail',
        ),
    ]
