# Generated by Django 3.1.1 on 2021-04-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=100)),
                ('tagBlog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.blogdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
