# Generated by Django 3.1.1 on 2021-04-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20210412_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
