# Generated by Django 3.1.1 on 2021-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_delete_blogtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('optional', models.TextField()),
                ('reportedBlog', models.CharField(max_length=200)),
            ],
        ),
    ]
