# Generated by Django 3.1.1 on 2021-04-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_reportedblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='blogName',
        ),
        migrations.AlterField(
            model_name='reportedblog',
            name='optional',
            field=models.TextField(blank=True),
        ),
    ]
