# Generated by Django 3.1.1 on 2021-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20210417_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='blogProfile',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
