# Generated by Django 3.1.1 on 2021-04-18 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_usersubscriber_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriber',
            name='AddOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
