# Generated by Django 3.1.1 on 2021-04-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20210418_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriber',
            name='AddOn',
        ),
    ]
