# Generated by Django 3.1.1 on 2021-04-18 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_remove_usersubscriber_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriber',
            name='AddOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
